version: '2.1'
services:
  kong-database:
    image: postgres:9.5
    environment:
      POSTGRES_USER: kong
      POSTGRES_DB: kong
    ports:
      - "5432:5432"
  kong:
    image: kong
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: kong-database
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_ADMIN_LISTEN: 0.0.0.0:8001
      KONG_ADMIN_LISTEN_SSL: 0.0.0.0:8444
    depends_on:
      - kong-database
    ports:
      - "8001:8001"
      - "8444:8444"
      - "8443:8443"
      - "8000:8000"
    command: kong start
  konga:
    image: pantsel/konga
    environment:
      NODE_ENV: production
      PORT: 1337
      DB_ADAPTER: postgres
      DB_URI: postgresql://kong@kong-database:5432/kong
      KONGA_HOOK_TIMEOUT: 120000
      KONGA_LOG_LEVEL: warn
      TOKEN_SECRET: random_secret
    ports:
      - "1337:1337" 
    depends_on:
      - kong-database
      - kong
# docker-compose run konga -c prepare -a postgres -u postgresql://kong@kong-database:5432/konga
